### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by sdaxini** [yschaeff/esp32-wifi-example#1]
First of all thanks for putting out a great sample. I am trying out your sample code, the scan detects the AP but is unable to connect. It keeps get a disconnected event without ever connecting... trying with esp-idf 2.1.

E (94150) wifi_network_up: Waiting for IP address...
E (96556) event_handler: disconnected

Any help appreciated.

**Comment by yschaeff** [comment]
I have no idea. But please note I wrote this ages ago (in internet years) and the ESP IDF is being developed quite extensively. So maybe something has changed in the IDF? I'd recommend trying the examples from the official documentation first for connecting to a AP.

**Comment by sdaxini** [comment]
Thanks for the response. The samples are there for scanning and connecting and both work separately but when I connect after a scan, I keep getting the disconnected msg but no IP. I guess some state issue which needs to be reset but havent been able to fix it. If I do find a solution, will post it back here.

**Comment by sdaxini** [comment]
Ok figured this out. On line 135, call esp_wifi_start(); before calling connect. Also my code was doing a synchronous scan which also was an issue, switch to async and wait for scan complete as in your code and it all works now. Hopefully this is useful to the next guy who tries your code. Thanks again.

**Comment by yschaeff** [comment]
Yeah I remember it took me quite a while to get it right at the time. Though not sure esp_wifi_start() in the loop makes sense. Anyway cheers!
